/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    VarButton: typeof import('@varlet/ui')['_ButtonComponent']
    VarCell: typeof import('@varlet/ui')['_CellComponent']
    VarDivider: typeof import('@varlet/ui')['_DividerComponent']
    VarIcon: typeof import('@varlet/ui')['_IconComponent']
    VarInput: typeof import('@varlet/ui')['_InputComponent']
    VarSpace: typeof import('@varlet/ui')['_SpaceComponent']
    Versions: typeof import('./src/components/Versions.vue')['default']
  }
}
